name: orto_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.3.1
  http: ^1.5.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  font_awesome_icon_class: ^0.0.6
  material_design_icons_flutter: ^7.0.7296
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/image/
